[package]
name = "settings_json"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/settings_json.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_lenient.workspace = true
serde_path_to_error.workspace = true
tree-sitter.workspace = true
tree-sitter-json.workspace = true
util.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
unindent.workspace = true

# Uncomment other workspace dependencies as needed
# assistant.workspace = true
# client.workspace = true
# project.workspace = true
# settings.workspace = true

[features]
default = []

[lints]
workspace = true
