[package]
name = "net"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
doctest = false
path = "src/net.rs"

[dependencies]
smol.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
async-io.workspace = true
windows.workspace = true

[lints]
workspace = true
