[package]
name = "askpass"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[package.metadata.cargo-shear]
ignored = ["log"]

[lib]
path = "src/askpass.rs"

[dependencies]
anyhow.workspace = true
futures.workspace = true
gpui.workspace = true
log.workspace = true
net.workspace = true
smol.workspace = true
tempfile.workspace = true
util.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true

[lints]
workspace = true
