[package]
name = "terminal"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
doctest = false
path = "src/terminal.rs"

[dependencies]
alacritty_terminal.workspace = true
anyhow.workspace = true
collections.workspace = true
futures.workspace = true
gpui.workspace = true
itertools.workspace = true
libc.workspace = true
log.workspace = true
regex.workspace = true
release_channel.workspace = true
schemars.workspace = true
serde.workspace = true
settings.workspace = true
smol.workspace = true
sysinfo.workspace = true
task.workspace = true
theme.workspace = true
thiserror.workspace = true
url.workspace = true
urlencoding.workspace = true
util.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
rand.workspace = true
settings = { workspace = true, features = ["test-support"] }
util_macros.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[features]
test-support = ["collections/test-support", "gpui/test-support", "settings/test-support"]

[lints]
workspace = true
