[package]
name = "node_runtime"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
doctest = false
path = "src/node_runtime.rs"

[dependencies]
anyhow.workspace = true
async-compression.workspace = true
async-tar.workspace = true
async-trait.workspace = true
futures.workspace = true
http_client.workspace = true
log.workspace = true
paths.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
smol.workspace = true
util.workspace = true
watch.workspace = true
which.workspace = true

[features]
test-support = []

[lints]
workspace = true
