[package]
name = "install_cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/install_cli.rs"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
release_channel.workspace = true
smol.workspace = true
util.workspace = true
workspace.workspace = true

[features]
test-support = []

[lints]
workspace = true
