[package]
name = "rpc"
version.workspace = true
edition.workspace = true
description = "Shared logic for communication between the MonyaCode app and the remote editing server"
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
doctest = false
path = "src/rpc.rs"

[dependencies]
anyhow.workspace = true
async-tungstenite.workspace = true
base64.workspace = true
chrono.workspace = true
collections.workspace = true
futures.workspace = true
gpui = { workspace = true, optional = true }
parking_lot.workspace = true
proto.workspace = true
rand.workspace = true
rsa.workspace = true
serde.workspace = true
sha2.workspace = true
strum.workspace = true
tracing.workspace = true
util.workspace = true
zstd.workspace = true

[dev-dependencies]
collections = { workspace = true, features = ["test-support"] }
gpui = { workspace = true, features = ["test-support"] }
proto = { workspace = true, features = ["test-support"] }
zlog.workspace = true

[features]
gpui = ["dep:gpui"]
test-support = ["collections/test-support", "gpui/test-support", "proto/test-support"]

[lints]
workspace = true
