[package]
name = "refineable"
version.workspace = true
edition.workspace = true
description = "A macro for creating 'refinement' types that can be used to partially initialize or mutate a complex struct"
repository.workspace = true
license = "Apache-2.0"
publish = false

[lib]
doctest = false
path = "src/refineable.rs"

[dependencies]
derive_refineable.workspace = true

[lints]
workspace = true
