[package]
name = "line_ending_selector"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
doctest = false
path = "src/line_ending_selector.rs"

[dependencies]
editor.workspace = true
gpui.workspace = true
language.workspace = true
picker.workspace = true
project.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true

[lints]
workspace = true
