[package]
name = "inspector_ui"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/inspector_ui.rs"

[dependencies]
anyhow.workspace = true
app_actions.workspace = true
command_palette_hooks.workspace = true
editor.workspace = true
fuzzy.workspace = true
gpui.workspace = true
language.workspace = true
project.workspace = true
serde_json.workspace = true
serde_json_lenient.workspace = true
theme.workspace = true
title_bar.workspace = true
ui.workspace = true
util.workspace = true
util_macros.workspace = true
workspace.workspace = true

[lints]
workspace = true
