[package]
name = "json_schema_store"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/json_schema_store.rs"

[dependencies]
anyhow.workspace = true
dap.workspace = true
extension.workspace = true
gpui.workspace = true
language.workspace = true
paths.workspace = true
project.workspace = true
schemars.workspace = true
serde_json.workspace = true
settings.workspace = true
snippet_provider.workspace = true
task.workspace = true
theme.workspace = true
util.workspace = true

[features]
default = []

[lints]
workspace = true
