[package]
name = "ui_prompt"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/ui_prompt.rs"

[dependencies]
gpui.workspace = true
markdown.workspace = true
menu.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
workspace.workspace = true

[features]
default = []

[lints]
workspace = true
